// Dog-friendly places on O'ahu.
// type: "off-leash" | "leashed"
// category: "dog-park" | "park" | "beach" | "trail"
// photo: optional image URL shown in the modal hero.
// uncertain: true shows a "Verify before visiting" badge.
// Researched July 2026 — rules and hours change; check posted signs.
const PARKS = [
  {
    "name": "Moanalua Dog Park",
    "lat": 21.3494,
    "lng": -157.8943,
    "type": "off-leash",
    "category": "dog-park",
    "address": "2900 Moanalua Rd, Honolulu, HI 96819 (Moanalua Community Park)",
    "hours": "Daily during daylight hours; closed Tuesday mornings for maintenance",
    "description": "A 1.3-acre fully fenced off-leash park inside Moanalua Community Park, one of the city's original and most popular dog parks.",
    "dogRules": "Off-leash allowed inside the fenced enclosure; dogs must be leashed to and from the gate. Water stations and waste bag dispensers provided.",
    "amenities": ["Fenced", "Water stations", "Waste bags", "Shade", "Benches", "Picnic tables", "Parking", "Restrooms nearby"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Elaine Dobashi Hawai'i Kai Dog Park",
    "lat": 21.2841,
    "lng": -157.7149,
    "type": "off-leash",
    "category": "dog-park",
    "address": "333 Keahole St, Honolulu, HI 96825 (behind Hawaii Kai Towne Center)",
    "hours": "Daily dawn to dusk; closed Tuesdays 7:00 AM - 12:00 PM for maintenance",
    "description": "O'ahu's largest off-leash dog park at roughly 1.65 acres, sitting along the Hawaii Kai marina area off Keahole Street.",
    "dogRules": "Fully fenced off-leash area with shade, seating and water; dogs must be licensed, vaccinated and leashed outside the enclosure.",
    "amenities": ["Fenced", "Water stations", "Waste bag dispensers", "Shade", "Seating", "Parking"],
    "region": "East Honolulu",
    "uncertain": false
  },
  {
    "name": "Mililani Dog Park",
    "lat": 21.4692,
    "lng": -158.0051,
    "type": "off-leash",
    "category": "dog-park",
    "address": "95-1069 Ukuwai St, Mililani, HI 96789 (Mililani Mauka District Park)",
    "hours": "Daily during daylight hours; closed Wednesday mornings for maintenance",
    "description": "Central O'ahu's flagship fenced dog park at Mililani Mauka District Park, with grassy runs and mature shade trees.",
    "dogRules": "Off-leash within the fenced park; separate maintenance closures posted on site. Water stations and cleanup bags available.",
    "amenities": ["Fenced", "Small & large dog areas", "Water stations", "Shade", "Benches", "Picnic tables", "Parking", "Restrooms nearby"],
    "region": "Central Oahu",
    "uncertain": false
  },
  {
    "name": "Ala Wai Dog Park",
    "lat": 21.2835,
    "lng": -157.8260,
    "type": "off-leash",
    "category": "dog-park",
    "address": "2444 Hihiwai St, Honolulu, HI 96826 (Ala Wai Community Park)",
    "hours": "Daily during daylight hours; closed Tuesday mornings for maintenance",
    "description": "A 15,000 sq ft fenced dog run beside the Ala Wai Canal, the closest off-leash park to Waikiki.",
    "dogRules": "Off-leash inside the fence with separate large-dog and small-dog sections; water spigot on site, leash required outside.",
    "amenities": ["Fenced", "Small & large dog areas", "Water spigot", "Seating", "Street parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Diamond Head Bark Park (Clark Hatch Bark Park)",
    "lat": 21.2672,
    "lng": -157.7988,
    "type": "off-leash",
    "category": "dog-park",
    "address": "4155 Diamond Head Rd, Honolulu, HI 96816",
    "hours": "Daily during daylight hours",
    "description": "Established in 1997 on the slopes of Diamond Head, this chain-link fenced bark park is one of Hawaii's oldest off-leash dog areas.",
    "dogRules": "Off-leash within the fenced park, with a smaller separate pen for small or anxious dogs; drinking fountain for dogs and shady trees.",
    "amenities": ["Fenced", "Small & large dog areas", "Water fountain", "Shade", "Benches", "Street parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "'A'ala Dog Park",
    "lat": 21.3155,
    "lng": -157.8638,
    "type": "off-leash",
    "category": "dog-park",
    "address": "280 N King St, Honolulu, HI 96817 ('A'ala Park, Chinatown)",
    "hours": "Daily 6:00 AM - 9:00 PM",
    "description": "An urban fenced dog park at the edge of 'A'ala Park near Chinatown and downtown Honolulu.",
    "dogRules": "Off-leash inside the fenced enclosure with separate small and large dog areas; leash required elsewhere in 'A'ala Park.",
    "amenities": ["Fenced", "Small & large dog areas", "Benches", "Street parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Hoa Aloha Dog Park",
    "lat": 21.3469,
    "lng": -157.9122,
    "type": "off-leash",
    "category": "dog-park",
    "address": "5080 Ala Loke St, Honolulu, HI 96818 (Salt Lake, at Hoa Aloha Neighborhood Park)",
    "hours": "Daily 5:00 AM - 8:00 PM; closed Tuesday mornings until noon",
    "description": "A 10,000 sq ft fenced neighborhood dog park serving the Salt Lake and Moanalua communities.",
    "dogRules": "Off-leash within the fence with designated large-dog and small-dog areas; dogs must be leashed outside the enclosure.",
    "amenities": ["Fenced", "Small & large dog areas", "Benches", "Street parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Hoalauna Dog Park",
    "lat": 21.3312,
    "lng": -158.0173,
    "type": "off-leash",
    "category": "dog-park",
    "address": "Keaunui Dr, 'Ewa Beach, HI 96706 ('Ewa Gentry)",
    "hours": "Daily during daylight hours",
    "description": "A fenced community dog park in the 'Ewa Gentry area serving 'Ewa Beach residents.",
    "dogRules": "Off-leash inside the fenced park with separate areas for large and small dogs; seating available, leash required outside.",
    "amenities": ["Fenced", "Small & large dog areas", "Seating", "Street parking"],
    "region": "Leeward",
    "uncertain": false
  },
  {
    "name": "Kaka'ako Dog Park (Mother Waldron Park)",
    "lat": 21.2995,
    "lng": -157.8588,
    "type": "off-leash",
    "category": "dog-park",
    "address": "690 Pohukaina St, Honolulu, HI 96813 (Mother Waldron Neighborhood Park)",
    "hours": "Daily 5:00 AM - 10:00 PM",
    "description": "A fenced off-leash run at Mother Waldron Neighborhood Park in the heart of the Kaka'ako district.",
    "dogRules": "Off-leash within the fenced area; note there is no dedicated parking and no water fountain, so bring your own water.",
    "amenities": ["Fenced", "Benches", "Street parking only", "No water on site"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Kahua O Waikalua Dog Park",
    "lat": 21.4076,
    "lng": -157.7930,
    "type": "off-leash",
    "category": "dog-park",
    "address": "45-231 Kulauli St, Kane'ohe, HI 96744",
    "hours": "Daily 7:00 AM - 7:00 PM; closed Thursdays 7:00 AM - 11:00 AM for maintenance",
    "description": "Windward O'ahu's first off-leash dog park, opened at Kahua O Waikalua Neighborhood Park in Kane'ohe.",
    "dogRules": "Off-leash inside the fence with separate large and small dog areas; benches, shade and drinking fountains provided.",
    "amenities": ["Fenced", "Small & large dog areas", "Water fountains", "Shade", "Benches", "Parking"],
    "region": "Windward",
    "uncertain": false
  },
  {
    "name": "Kolowalu Dog Park",
    "lat": 21.2913,
    "lng": -157.8493,
    "type": "off-leash",
    "category": "dog-park",
    "address": "1240 Ala Moana Blvd, Honolulu, HI 96814 (Kolowalu Park, Ward Village)",
    "hours": "Daily 6:00 AM - 10:00 PM",
    "description": "Opened in February 2025 in Ward Village's Kolowalu Park, a modern fenced dog run steps from Ala Moana Beach Park.",
    "dogRules": "Off-leash within the fenced enclosure with separate large-dog and small-dog areas; leash required in the rest of the park.",
    "amenities": ["Fenced", "Small & large dog areas", "Seating", "Nearby paid parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Mo'ili'ili Dog Park (Kalo Place Mini Park)",
    "lat": 21.2917,
    "lng": -157.8193,
    "type": "off-leash",
    "category": "dog-park",
    "address": "2705 Varsity Pl, Honolulu, HI 96826",
    "hours": "Daily 5:00 AM - 10:00 PM; closed Tuesdays 7:00 AM - 12:00 PM for maintenance",
    "description": "A compact fenced dog park at Kalo Place Mini Park near the University of Hawai'i at Manoa.",
    "dogRules": "Off-leash inside the fence with separate small and large dog sections; street parking is limited.",
    "amenities": ["Fenced", "Small & large dog areas", "Benches", "Limited street parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Patsy T. Mink Central O'ahu Dog Park",
    "lat": 21.4086,
    "lng": -158.0097,
    "type": "off-leash",
    "category": "dog-park",
    "address": "94-580 Lumiauau St, Waipahu, HI 96797 (makai end of Central O'ahu Regional Park, where Paiwa St ends)",
    "hours": "Daily during daylight hours",
    "description": "A 12,800 sq ft fenced lawn with a distinctive parallelogram design at the makai end of Patsy T. Mink Central O'ahu Regional Park, opened in 2021.",
    "dogRules": "Off-leash within the fence with separate big-dog and small-dog areas; drinking fountains, irrigation/sprinklers, and ADA-accessible paths.",
    "amenities": ["Fenced", "Small & large dog areas", "Water fountains", "Benches", "ADA accessible", "Parking"],
    "region": "Central Oahu",
    "uncertain": false
  },
  {
    "name": "Punahou Square Off-Leash Dog Park",
    "lat": 21.3022,
    "lng": -157.8331,
    "type": "off-leash",
    "category": "dog-park",
    "address": "1526 Punahou St, Honolulu, HI 96822 (Makiki)",
    "hours": "Daily sunrise to sunset; closed Tuesday mornings for maintenance",
    "description": "The city's newest off-leash dog park, opened December 2025/January 2026 — about half an acre of fenced space shaded by a huge Moreton Bay fig tree.",
    "dogRules": "Off-leash within the fenced enclosure; dogs must be licensed and vaccinated, and leashed outside the gates.",
    "amenities": ["Fenced", "Shade", "Benches", "Street parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Schuler Family Foundation & Jones Family Community Dog Park",
    "lat": 21.3604,
    "lng": -158.0292,
    "type": "off-leash",
    "category": "dog-park",
    "address": "91-1945 Fort Weaver Rd, 'Ewa Beach, HI 96706 (Hawaiian Humane Society Kosasa Family Campus at Ho'opili)",
    "hours": "Wed-Mon 11:00 AM - 6:00 PM; closed Tuesdays for maintenance",
    "description": "Opened May 2025 at the Hawaiian Humane Society's Kosasa Family Campus, this members-only community dog park effectively replaces the society's former McInerny Dog Park in Mo'ili'ili, which is permanently closed.",
    "dogRules": "Off-leash for registered members only (registration is free, donations encouraged); separate small and large dog areas, play structures, gazebos and water.",
    "amenities": ["Fenced", "Small & large dog areas", "Water stations", "Play structures", "Gazebos/shade", "Parking", "Free membership required"],
    "region": "Leeward",
    "uncertain": false
  },
  {
    "name": "Kailua Beach Park",
    "lat": 21.3966,
    "lng": -157.7259,
    "type": "leashed",
    "category": "beach",
    "address": "526 Kawailoa Rd, Kailua, HI 96734",
    "hours": "Daily 5:00 AM - 10:00 PM (typical county beach park hours)",
    "description": "One of O'ahu's most famous white-sand beaches, with calm turquoise water, big lawns, and full facilities — newly designated a city on-leash dog park in February 2026.",
    "dogRules": "Leashed dogs are now officially allowed under the city's 2026 on-leash park designation; pick up after your dog and keep leash on at all times.",
    "amenities": ["Beach access", "Parking", "Restrooms", "Showers", "Picnic areas", "Shade"],
    "region": "Windward",
    "uncertain": false
  },
  {
    "name": "Sandy Beach Park",
    "lat": 21.2857,
    "lng": -157.6725,
    "type": "leashed",
    "category": "beach",
    "address": "8801 Kalaniana'ole Hwy, Honolulu, HI 96825",
    "hours": "Daily 5:00 AM - 10:00 PM (typical county beach park hours)",
    "description": "A famous bodysurfing beach on the wild Ka Iwi coast with big lawns, dunes, and dramatic shoreline; on the city's official on-leash dog park list.",
    "dogRules": "Leashed dogs allowed in the park; the shorebreak is powerful and dangerous, so keep dogs away from the water's edge.",
    "amenities": ["Beach access", "Large lawns", "Parking", "Restrooms", "Showers"],
    "region": "East Honolulu",
    "uncertain": false
  },
  {
    "name": "Kaka'ako Waterfront Park",
    "lat": 21.2931,
    "lng": -157.8635,
    "type": "leashed",
    "category": "park",
    "address": "102 Ohe St, Honolulu, HI 96813",
    "hours": "Daily 6:00 AM - 10:00 PM",
    "description": "A grassy oceanfront promenade park with rolling hills and sweeping views from Diamond Head to the harbor.",
    "dogRules": "Leashed dogs allowed throughout the park's lawns and paths; no swimming beach — clean up after your dog.",
    "amenities": ["Oceanfront paths", "Large lawns", "Parking", "Restrooms", "Picnic tables"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Ke'ehi Lagoon Beach Park",
    "lat": 21.3309,
    "lng": -157.8984,
    "type": "leashed",
    "category": "park",
    "address": "465 Lagoon Dr, Honolulu, HI 96819",
    "hours": "Daily 5:00 AM - 10:00 PM (typical county park hours)",
    "description": "A large, flat waterfront park near the airport with huge open fields, canoe halau and shaded picnic areas; on the city's on-leash dog park list.",
    "dogRules": "Leashed dogs allowed in park areas; plenty of open space for long on-leash walks.",
    "amenities": ["Large lawns", "Parking", "Restrooms", "Picnic tables", "Shade"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Neal S. Blaisdell Park",
    "lat": 21.3853,
    "lng": -157.9549,
    "type": "leashed",
    "category": "park",
    "address": "98-319 Kamehameha Hwy, 'Aiea, HI 96701",
    "hours": "Daily 5:00 AM - 10:00 PM (typical county park hours)",
    "description": "A shoreline park on Pearl Harbor's East Loch connected to the Pearl Harbor Historic Trail bike path, popular for dog walking.",
    "dogRules": "Leashed dogs allowed in the park and along the adjacent multi-use path; clean up required.",
    "amenities": ["Waterfront path", "Parking", "Restrooms", "Picnic areas", "Shade"],
    "region": "Central Oahu",
    "uncertain": false
  },
  {
    "name": "Hale'iwa Beach Park",
    "lat": 21.5983,
    "lng": -158.1033,
    "type": "leashed",
    "category": "beach",
    "address": "62-449 Kamehameha Hwy, Hale'iwa, HI 96712",
    "hours": "Daily 5:00 AM - 10:00 PM (typical county beach park hours)",
    "description": "A calm, protected beach park at the north end of Hale'iwa town with lawns, sports fields and gentle water; on the city's on-leash list.",
    "dogRules": "Leashed dogs allowed in the park under the city's 2026 on-leash designation; keep dogs leashed and pick up waste.",
    "amenities": ["Beach access", "Calm water", "Large lawns", "Parking", "Restrooms", "Showers"],
    "region": "North Shore",
    "uncertain": false
  },
  {
    "name": "Bill and Peggy Paty Kaiaka Bay Beach Park",
    "lat": 21.5869,
    "lng": -158.1160,
    "type": "leashed",
    "category": "beach",
    "address": "66-449 Hale'iwa Rd, Hale'iwa, HI 96712",
    "hours": "Daylight hours (gated park; gate closed overnight)",
    "description": "A quiet 53-acre wooded beach park on Kaiaka Bay west of Hale'iwa town, with campsites and shady ironwood trees.",
    "dogRules": "Leashed dogs allowed in the park under the city's on-leash designation; keep dogs leashed at all times.",
    "amenities": ["Beach access", "Shade", "Parking", "Restrooms", "Picnic tables", "Camping"],
    "region": "North Shore",
    "uncertain": false
  },
  {
    "name": "Mokule'ia Beach Park",
    "lat": 21.5818,
    "lng": -158.1925,
    "type": "leashed",
    "category": "beach",
    "address": "68-919 Farrington Hwy, Waialua, HI 96791 (across from Dillingham Airfield)",
    "hours": "Daily 5:00 AM - 10:00 PM (typical county beach park hours)",
    "description": "A remote, uncrowded stretch of white sand on the far North Shore across from Dillingham Airfield; on the city's on-leash dog park list.",
    "dogRules": "Leashed dogs allowed; the area is undeveloped and quiet, ideal for long on-leash beach walks. Strong currents in winter.",
    "amenities": ["Beach access", "Parking", "Restrooms", "Picnic tables", "Camping"],
    "region": "North Shore",
    "uncertain": false
  },
  {
    "name": "Kalaeloa Beach Park",
    "lat": 21.3013,
    "lng": -158.0580,
    "type": "leashed",
    "category": "beach",
    "address": "Eisenhower Rd, Kalaeloa ('Ewa Beach), HI 96706",
    "hours": "Daily during daylight hours",
    "description": "A low-key leeward shoreline park in the former Barbers Point area with reef-protected coves; on the city's on-leash dog park list.",
    "dogRules": "Leashed dogs allowed in the park; keep dogs leashed and carry out waste — facilities are minimal.",
    "amenities": ["Beach access", "Parking", "Limited facilities"],
    "region": "Leeward",
    "uncertain": false
  },
  {
    "name": "One'ula Beach Park",
    "lat": 21.3059,
    "lng": -158.0308,
    "type": "leashed",
    "category": "beach",
    "address": "91-101 Papipi Rd, 'Ewa Beach, HI 96706",
    "hours": "Daily 5:00 AM - 10:00 PM (typical county beach park hours)",
    "description": "A spacious, locals-favorite shoreline park in 'Ewa Beach known as 'Hau Bush,' with a long rocky-sand coastline and big open areas.",
    "dogRules": "Frequently cited as dog-friendly with leashed dogs welcome, but it does NOT appear on the city's official on-leash park list — verify current signage before relying on it.",
    "amenities": ["Beach access", "Parking", "Restrooms", "Open space"],
    "region": "Leeward",
    "uncertain": true
  },
  {
    "name": "Manoa Falls Trail",
    "lat": 21.3314,
    "lng": -157.8012,
    "type": "leashed",
    "category": "trail",
    "address": "End of Manoa Rd (3860 Manoa Rd area), Honolulu, HI 96822 — paid lot at Paradise Park",
    "hours": "Daily during daylight hours; paid parking lot roughly 7:00 AM - 6:00 PM",
    "description": "A lush 1.6-mile round-trip rainforest hike through bamboo and banyan to a 150-foot waterfall, one of Honolulu's most popular trails (Na Ala Hele).",
    "dogRules": "Leashed dogs allowed under Na Ala Hele rules; trail is often muddy, and dogs must stay leashed and be cleaned up after.",
    "amenities": ["Paid parking", "Restrooms at trailhead", "Shade", "Waterfall"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "'Aiea Loop Trail (Keaiwa Heiau State Recreation Area)",
    "lat": 21.3985,
    "lng": -157.9007,
    "type": "leashed",
    "category": "trail",
    "address": "99-1849 'Aiea Heights Dr, 'Aiea, HI 96701 (upper trailhead inside Keaiwa Heiau SRA)",
    "hours": "Gates daily 7:00 AM - 7:45 PM (Apr-early Sep); 7:00 AM - 6:45 PM rest of year",
    "description": "A 4.8-mile ridge loop through eucalyptus and native forest above Halawa Valley, with picnic areas and ample parking in the state recreation area.",
    "dogRules": "Leashed dogs welcome on the loop trail; state park rules require dogs on leash at all times and waste pickup.",
    "amenities": ["Parking", "Restrooms", "Picnic areas", "Shade", "Camping nearby"],
    "region": "Central Oahu",
    "uncertain": false
  },
  {
    "name": "Kuli'ou'ou Ridge Trail",
    "lat": 21.3036,
    "lng": -157.7242,
    "type": "leashed",
    "category": "trail",
    "address": "Trailhead at end of Kala'au Pl, Honolulu, HI 96821 (street parking in residential neighborhood)",
    "hours": "Daily during daylight hours",
    "description": "A challenging 5-mile round-trip Na Ala Hele ridge hike through ironwood and Cook pine forest to a Ko'olau summit with panoramic windward views.",
    "dogRules": "Leashed dogs allowed under Na Ala Hele rules; keep dogs leashed — the upper stairs and summit section are steep and exposed.",
    "amenities": ["Street parking", "Shade on lower trail", "Covered rest shelters"],
    "region": "East Honolulu",
    "uncertain": false
  },
  {
    "name": "Makapu'u Point Lighthouse Trail",
    "lat": 21.3040,
    "lng": -157.6553,
    "type": "leashed",
    "category": "trail",
    "address": "Makapu'u Lighthouse Rd off Kalaniana'ole Hwy, Waimanalo, HI 96795 (Kaiwi State Scenic Shoreline parking lot)",
    "hours": "Gates daily 7:00 AM - 7:45 PM (summer); closes 6:45 PM rest of year",
    "description": "A paved 2-mile round-trip trail climbing to the Makapu'u lighthouse overlook, with whale watching in winter and sweeping views of the southeastern coast.",
    "dogRules": "Leashed dogs allowed; the paved path gets very hot at midday, so go early or late to protect paws. Clean up after your dog.",
    "amenities": ["Parking", "Paved trail", "Scenic overlooks", "No water or restrooms"],
    "region": "East Honolulu",
    "uncertain": false
  },
  {
    "name": "Wa'ahila Ridge Trail (Wa'ahila Ridge State Recreation Area)",
    "lat": 21.3059,
    "lng": -157.7999,
    "type": "leashed",
    "category": "trail",
    "address": "Top of Ruth Pl via St. Louis Heights Dr, Honolulu, HI 96816",
    "hours": "Gates daily 7:00 AM - 7:45 PM (summer); closes 6:45 PM rest of year",
    "description": "A Na Ala Hele ridge trail starting in a Cook pine grove above St. Louis Heights, rolling along the ridge between Manoa and Palolo valleys (~4.8 miles round trip).",
    "dogRules": "Leashed dogs welcome under state park and Na Ala Hele rules; picnic areas at the trailhead make it an easy shorter outing too.",
    "amenities": ["Parking", "Restrooms", "Picnic areas", "Shade"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Ka'iwa Ridge (Lanikai Pillbox) Trail",
    "lat": 21.3928,
    "lng": -157.7216,
    "type": "leashed",
    "category": "trail",
    "address": "Ka'iwa Ridge Trailhead, 265 Kaelepulu Drive, Kailua, HI 96734",
    "hours": "Sunrise to sunset (daily)",
    "description": "A short but steep 1.8-mile out-and-back ridge hike to two WWII pillboxes with sweeping views over Lanikai, the Mokulua islands, and Kailua Bay. One of the most popular quick-summit hikes on the Windward side.",
    "dogRules": "Dogs are welcome but must be kept on a leash at all times; bring water as there is no shade and it gets hot on the exposed ridge.",
    "amenities": ["Street parking", "Ocean views", "No restrooms", "No water"],
    "region": "Windward",
    "uncertain": false
  },
  {
    "name": "Judd Trail (Judd Memorial Loop)",
    "lat": 21.3535,
    "lng": -157.8116,
    "type": "leashed",
    "category": "trail",
    "address": "Judd Trailhead, 4022 Nuuanu Pali Drive, Honolulu, HI 96817",
    "hours": "Sunrise to sunset (daily)",
    "description": "A shady 1.2-mile loop through Nuuanu Valley's bamboo and eucalyptus groves, passing the Jackass Ginger swimming hole. An easy, family-friendly forest walk close to town.",
    "dogRules": "Dogs are allowed but must remain on a leash; the connecting Nu'uanu Trail does NOT allow dogs, so stay on the Judd loop.",
    "amenities": ["Roadside parking", "Stream", "Shade", "Swimming hole", "No restrooms"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Pu'u O Hulu (Pink Pillbox) Trail",
    "lat": 21.4183,
    "lng": -158.1710,
    "type": "leashed",
    "category": "trail",
    "address": "Kaukama Road Trailhead, Ma'ili, Waianae, HI 96792",
    "hours": "Sunrise to sunset (daily)",
    "description": "A steep 1.5-mile out-and-back climb to a chain of pink-painted pillboxes above Ma'ili, with panoramic Leeward coast and ocean views. Quick but demanding, gaining roughly 700 feet.",
    "dogRules": "Dogs are welcome on a leash; the climb is steep and exposed with no shade or water, so it is best for fit dogs in cooler hours.",
    "amenities": ["Roadside parking", "Ocean views", "No restrooms", "No water"],
    "region": "Leeward",
    "uncertain": false
  },
  {
    "name": "Koko Crater Railway Trail",
    "lat": 21.2818,
    "lng": -157.6947,
    "type": "leashed",
    "category": "trail",
    "address": "Koko Head District Park, 7604 Koko Head Park Road, Honolulu, HI 96825",
    "hours": "Sunrise to sunset (daily)",
    "description": "A grueling 1.8-mile out-and-back straight up an old military tramway of over 1,000 railroad ties to the summit of Koko Crater, rewarding hikers with 360-degree views of Hawai'i Kai and Hanauma Bay.",
    "dogRules": "Sources conflict on whether dogs are permitted, and even where allowed the steep, exposed railroad ties and lack of shade or water make it hazardous for dogs; verify current policy before bringing a dog.",
    "amenities": ["Park parking", "Restrooms at base park", "No shade", "No water on trail"],
    "region": "East Honolulu",
    "uncertain": true
  },
  {
    "name": "Hale'iwa Ali'i Beach Park",
    "lat": 21.5930,
    "lng": -158.1100,
    "type": "leashed",
    "category": "beach",
    "address": "66-167 Hale'iwa Road, Hale'iwa, HI 96712",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A wide North Shore beach park on Waialua Bay known for surf, sea turtles, and a grassy shoreline. A designated on-leash park with lifeguards and lots of open space.",
    "dogRules": "Leashed dogs are allowed under the City & County of Honolulu on-leash park designation; keep dogs leashed and clean up after them.",
    "amenities": ["Parking", "Restrooms", "Showers", "Lifeguard", "Picnic tables", "Grassy areas"],
    "region": "North Shore",
    "uncertain": false
  },
  {
    "name": "'Aweoweo Beach Park",
    "lat": 21.5824,
    "lng": -158.1372,
    "type": "leashed",
    "category": "beach",
    "address": "68-197 Au Street, Waialua, HI 96791",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A quiet, local neighborhood beach park in Waialua with a sandy shore, grassy lawn, and playground. Far less crowded than the main North Shore beaches.",
    "dogRules": "Leashed dogs are allowed under the City on-leash park designation; keep dogs on leash and pick up waste.",
    "amenities": ["Parking", "Restrooms", "Showers", "Playground", "Picnic tables"],
    "region": "North Shore",
    "uncertain": false
  },
  {
    "name": "Waialua District Park",
    "lat": 21.5727,
    "lng": -158.1320,
    "type": "leashed",
    "category": "park",
    "address": "67-180 Goodale Avenue, Waialua, HI 96791",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A large community district park in the town of Waialua with sports fields, a gym, and open lawns. A newly designated on-leash park serving the North Shore.",
    "dogRules": "Leashed dogs are permitted under the City on-leash park designation; leash and clean-up required.",
    "amenities": ["Parking", "Restrooms", "Sports fields", "Gymnasium", "Grassy areas"],
    "region": "North Shore",
    "uncertain": false
  },
  {
    "name": "Halawa District Park",
    "lat": 21.3838,
    "lng": -157.9223,
    "type": "leashed",
    "category": "park",
    "address": "99-795 'Iwa'iwa Street, 'Aiea, HI 96701",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A spacious district park in Halawa/'Aiea with athletic fields, courts, and grassy open areas backed by the Ko'olau foothills. A designated on-leash park in the Pearl Harbor corridor.",
    "dogRules": "Leashed dogs are allowed under the City on-leash park designation; keep dogs leashed and clean up after them.",
    "amenities": ["Parking", "Restrooms", "Sports fields", "Tennis courts", "Grassy areas"],
    "region": "Central Oahu",
    "uncertain": false
  },
  {
    "name": "Pearl Ridge Community Park",
    "lat": 21.3862,
    "lng": -157.9432,
    "type": "leashed",
    "category": "park",
    "address": "98-960 Moanalua Road, 'Aiea, HI 96701",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A neighborhood community park in 'Aiea near Pearlridge with lawns, a playground, and walking paths. Convenient green space now open to leashed dogs.",
    "dogRules": "Leashed dogs are allowed under the City on-leash park designation; leash required and owners must clean up.",
    "amenities": ["Parking", "Restrooms", "Playground", "Grassy areas", "Walking paths"],
    "region": "Central Oahu",
    "uncertain": false
  },
  {
    "name": "Mililani District Park",
    "lat": 21.4560,
    "lng": -158.0110,
    "type": "leashed",
    "category": "park",
    "address": "94-1150 Lanikuhana Avenue, Mililani, HI 96789",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A central Mililani district park with a swimming pool, sports fields, courts, and expansive lawns. A large designated on-leash park in Central O'ahu.",
    "dogRules": "Leashed dogs are permitted under the City on-leash park designation; keep dogs leashed and pick up after them.",
    "amenities": ["Parking", "Restrooms", "Swimming pool", "Sports fields", "Tennis courts", "Grassy areas"],
    "region": "Central Oahu",
    "uncertain": false
  },
  {
    "name": "Dole Community Park",
    "lat": 21.3160,
    "lng": -157.8370,
    "type": "leashed",
    "category": "park",
    "address": "602 Magellan Avenue, Honolulu, HI 96813",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A small community park in the Papakolea/Punchbowl area above downtown Honolulu with a playground and open lawn. A neighborhood green space newly designated for on-leash dogs.",
    "dogRules": "Leashed dogs are allowed under the City on-leash park designation; leash and clean-up required.",
    "amenities": ["Street parking", "Playground", "Grassy areas"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Maunalani Community Park",
    "lat": 21.2975,
    "lng": -157.7920,
    "type": "leashed",
    "category": "park",
    "address": "4625 Sierra Drive, Honolulu, HI 96816",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A hillside neighborhood park on Wilhelmina Rise above Kaimuki with lawns and elevated city views. A quiet designated on-leash park.",
    "dogRules": "Leashed dogs are allowed under the City on-leash park designation; keep dogs leashed and clean up after them.",
    "amenities": ["Street parking", "Grassy areas", "City views", "Playground"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Kamilo Iki Neighborhood Park",
    "lat": 21.3025,
    "lng": -157.7015,
    "type": "leashed",
    "category": "park",
    "address": "7750 Hawaii Kai Drive, Honolulu, HI 96825",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A neighborhood park in the Kamilo'iki valley of Hawai'i Kai with sports fields, a skate park, and open lawns. A designated on-leash park in East Honolulu.",
    "dogRules": "Leashed dogs are permitted under the City on-leash park designation; leash required and clean up after your dog.",
    "amenities": ["Parking", "Restrooms", "Sports fields", "Skate park", "Grassy areas"],
    "region": "East Honolulu",
    "uncertain": false
  },
  {
    "name": "Maunawili Valley Neighborhood Park",
    "lat": 21.3617,
    "lng": -157.7607,
    "type": "leashed",
    "category": "park",
    "address": "962 Maunawili Road, Kailua, HI 96734",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A green neighborhood park nestled in Maunawili Valley beneath the Ko'olau range, with fields, courts, and lawns. A designated on-leash park on the Windward side.",
    "dogRules": "Leashed dogs are allowed under the City on-leash park designation; keep dogs leashed and clean up after them.",
    "amenities": ["Parking", "Restrooms", "Sports fields", "Tennis courts", "Grassy areas"],
    "region": "Windward",
    "uncertain": false
  },
  {
    "name": "Makakilo Neighborhood Park",
    "lat": 21.3667,
    "lng": -158.0862,
    "type": "leashed",
    "category": "park",
    "address": "92-665 Anipeahi Street, Kapolei, HI 96707",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A hillside neighborhood park in Makakilo above Kapolei with a playground, court, and lawns offering breezy Leeward views. A designated on-leash park.",
    "dogRules": "Leashed dogs are permitted under the City on-leash park designation; leash and clean-up required.",
    "amenities": ["Parking", "Playground", "Basketball court", "Grassy areas"],
    "region": "Leeward",
    "uncertain": false
  },
  {
    "name": "Palailai Neighborhood Park",
    "lat": 21.3563,
    "lng": -158.0785,
    "type": "leashed",
    "category": "park",
    "address": "92-1291 Palahia Street, Kapolei, HI 96707",
    "hours": "5:00 AM - 10:00 PM (daily)",
    "description": "A neighborhood park in the Makakilo/Kapolei area with open lawns and a playground serving the surrounding community. A designated on-leash park in the Leeward district.",
    "dogRules": "Leashed dogs are allowed under the City on-leash park designation; keep dogs leashed and clean up after them.",
    "amenities": ["Parking", "Playground", "Grassy areas"],
    "region": "Leeward",
    "uncertain": false
  },
  {
    "name": "Kahiwelo Neighborhood Park",
    "lat": 21.3455216,
    "lng": -158.0753866,
    "type": "leashed",
    "category": "park",
    "address": "92-2100 Kulihi St, Kapolei, HI 96707",
    "hours": "Daily 5:00 AM - 10:00 PM",
    "description": "A quiet neighborhood park in the upper Makakilo (Kahiwelo) subdivision with open grass, a playground and sweeping views toward the coast. Newly designated on-leash for dogs in the City's February 2026 expansion.",
    "dogRules": "Dogs must be kept on a leash no longer than six feet at all times. Owners are required to pick up and dispose of all pet waste.",
    "amenities": ["Open lawn", "Playground", "Street parking", "Scenic views"],
    "region": "Leeward",
    "uncertain": false
  },
  {
    "name": "Kaoma'aiku Neighborhood Park",
    "lat": 21.4610327,
    "lng": -158.0001068,
    "type": "leashed",
    "category": "park",
    "address": "95-1000 Maka'unulau St, Mililani, HI 96789",
    "hours": "Daily 5:00 AM - 10:00 PM",
    "description": "A roughly 10-acre Mililani Mauka park with sports fields, an inline hockey rink and open turf that recently gained extended daily hours. Added to the City's on-leash dog park list in February 2026.",
    "dogRules": "Dogs are welcome on a leash of six feet or less; keep pets off active sports fields and clean up after them.",
    "amenities": ["Sports fields", "Inline hockey rink", "Parking", "Restrooms"],
    "region": "Central Oahu",
    "uncertain": false
  },
  {
    "name": "Kipapa Neighborhood Park",
    "lat": 21.4399635,
    "lng": -158.0153986,
    "type": "leashed",
    "category": "park",
    "address": "95-439 Kuahelani Ave, Mililani, HI 96789",
    "hours": "Daily 5:00 AM - 10:00 PM",
    "description": "A neighborhood park in older Mililani Town beside Kipapa Elementary, with grassy areas and a playground popular with local families. Newly designated on-leash for dogs in 2026.",
    "dogRules": "Leashed dogs only (six-foot maximum leash); owners must remove all waste.",
    "amenities": ["Open lawn", "Playground", "Street parking"],
    "region": "Central Oahu",
    "uncertain": true
  },
  {
    "name": "Makiki Street Mini Park",
    "lat": 21.3061086,
    "lng": -157.8324817,
    "type": "leashed",
    "category": "park",
    "address": "1841 Makiki St, Honolulu, HI 96822",
    "hours": "Daily, sunrise to sunset",
    "description": "A tiny 0.15-acre pocket park at the corner of Makiki and Nehoa Streets offering a shady patch of green in the Makiki neighborhood. One of Honolulu's smallest parks, newly opened to leashed dogs in 2026.",
    "dogRules": "Dogs must remain leashed (six feet or less) and owners must pick up after them; space is very limited.",
    "amenities": ["Benches", "Shade trees", "Street parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Pawa'a In-Ha Park",
    "lat": 21.2982615,
    "lng": -157.8382835,
    "type": "leashed",
    "category": "park",
    "address": "1461 Young St, Honolulu, HI 96814",
    "hours": "Daily, sunrise to sunset",
    "description": "A small urban park between Young and King Streets in the Pawa'a area of central Honolulu, with lawn, benches and a play area. Recently designated on-leash for dogs.",
    "dogRules": "Keep dogs on a leash no longer than six feet and clean up all waste.",
    "amenities": ["Open lawn", "Benches", "Playground", "Street parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Pu'unui Community Park",
    "lat": 21.3343370,
    "lng": -157.8479328,
    "type": "leashed",
    "category": "park",
    "address": "2555 Puunui Ave, Honolulu, HI 96817",
    "hours": "Daily, sunrise to sunset",
    "description": "A community park in the Nu'uanu/Pu'unui area with a multipurpose field, basketball court and community building. Newly added to the City's on-leash dog park list in February 2026.",
    "dogRules": "Leashed dogs only (six-foot maximum); owners must remove pet waste and avoid the sports court and building interior.",
    "amenities": ["Multipurpose field", "Basketball court", "Community building", "Parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Waialae Iki Neighborhood Park",
    "lat": 21.2771105,
    "lng": -157.7688841,
    "type": "leashed",
    "category": "park",
    "address": "4838 Kalanianaole Hwy, Honolulu, HI 96821",
    "hours": "Daily, sunrise to sunset",
    "description": "A neighborhood park in the Waialae Iki hills of East Honolulu with a playground, court and open grassy space. One of the pilot sites for the City's new dog-park signage and waste-bag dispensers rolled out in 2026.",
    "dogRules": "Dogs are allowed on a leash of six feet or less; free waste bags are provided and owners must clean up.",
    "amenities": ["Playground", "Basketball court", "Open lawn", "Waste bag dispenser", "Parking"],
    "region": "East Honolulu",
    "uncertain": false
  },
  {
    "name": "Enchanted Lake Community Park",
    "lat": 21.3799465,
    "lng": -157.7288026,
    "type": "leashed",
    "category": "park",
    "address": "770 Keolu Dr, Kailua, HI 96734",
    "hours": "Daily, sunrise to sunset",
    "description": "A large community park in Kailua's Enchanted Lake neighborhood with expansive fields, a playground and space used for dog agility events. A pilot site for the City's new on-leash dog signage and waste-bag dispensers.",
    "dogRules": "Leashed dogs only (six-foot maximum leash); free waste bags provided and owners must dispose of waste.",
    "amenities": ["Large open fields", "Playground", "Waste bag dispenser", "Parking", "Restrooms"],
    "region": "Windward",
    "uncertain": false
  },
  {
    "name": "Ewa Beach Community Park",
    "lat": 21.3146089,
    "lng": -158.0072268,
    "type": "leashed",
    "category": "park",
    "address": "91-955 North Rd, Ewa Beach, HI 96706",
    "hours": "Daily, sunrise to sunset",
    "description": "An inland community park in Ewa Beach with sports fields, courts and a community center hosting an open market. A pilot site for the City's new dog-park signage and dog-waste bag dispensers.",
    "dogRules": "Dogs must be leashed (six feet or less); owners must pick up after their pets using the provided waste bags.",
    "amenities": ["Sports fields", "Courts", "Community center", "Waste bag dispenser", "Parking"],
    "region": "Leeward",
    "uncertain": false
  },
  {
    "name": "Sunset Point Beach Park",
    "lat": 21.6639086,
    "lng": -158.0505677,
    "type": "leashed",
    "category": "beach",
    "address": "Kamehameha Hwy, Pupukea, Haleiwa, HI 96712",
    "hours": "Daily, sunrise to sunset",
    "description": "A small North Shore beach park near the famous Sunset Beach stretch in Pupukea, with calm summer swimming and legendary winter surf nearby. Newly designated on-leash for dogs in 2026.",
    "dogRules": "Leashed dogs only (six-foot maximum); owners must remove all waste and mind surf and shorebreak conditions.",
    "amenities": ["Sandy beach", "Nearby restrooms", "Street parking"],
    "region": "North Shore",
    "uncertain": true
  },
  {
    "name": "Waialua Bandstand Park",
    "lat": 21.5700838,
    "lng": -158.1226828,
    "type": "leashed",
    "category": "park",
    "address": "Goodale Ave, Waialua, HI 96791",
    "hours": "Daily, sunrise to sunset",
    "description": "A small historic park on Goodale Avenue in Waialua town centered on a restored community bandstand, with lawn and shade trees. Added to the City's on-leash dog list in February 2026.",
    "dogRules": "Dogs must be leashed (six feet or less) and owners must clean up after them.",
    "amenities": ["Historic bandstand", "Open lawn", "Shade trees", "Street parking"],
    "region": "North Shore",
    "uncertain": true
  },
  {
    "name": "Kawailoa Beach Park",
    "lat": 21.6280556,
    "lng": -158.0800000,
    "type": "leashed",
    "category": "beach",
    "address": "Kamehameha Hwy, Haleiwa, HI 96712",
    "hours": "Daily, sunrise to sunset",
    "description": "A wide, uncrowded North Shore sand beach along Kamehameha Highway next to the Chun's Reef surf spot, between Haleiwa and Waimea Bay. Newly opened to leashed dogs in 2026.",
    "dogRules": "Leashed dogs only (six-foot maximum leash); owners must pack out all waste. No lifeguard - mind strong winter surf.",
    "amenities": ["Long sandy beach", "Surf spot", "Roadside parking only"],
    "region": "North Shore",
    "uncertain": true
  },
  {
    "name": "Aloha Beer Co.",
    "lat": 21.2957,
    "lng": -157.8562,
    "type": "leashed",
    "category": "patio",
    "address": "700 Queen St, Honolulu, HI 96813",
    "hours": "Mon-Thu 3pm-10pm, Fri 3pm-12am, Sat 11:30am-12am, Sun 11:30am-9pm",
    "description": "A popular Kaka'ako brewpub and beer garden with a large open-air lanai serving craft beers and Fatto a Mano pizza. A longtime favorite for dog owners in the neighborhood.",
    "dogRules": "Leashed dogs welcome in the outdoor lanai/beer garden only. They offer a dog menu including a chicken, veggie, bacon and egg 'bibim-pup' bowl.",
    "amenities": ["Outdoor patio", "Beer garden", "Shade", "Dog menu", "Water bowls"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Waikiki Brewing Company (Kaka'ako)",
    "lat": 21.2949,
    "lng": -157.8583,
    "type": "leashed",
    "category": "patio",
    "address": "831 Queen St, Honolulu, HI 96813",
    "hours": "Daily 11am-10pm",
    "description": "A local craft brewery in Kaka'ako with an on-site barbecue menu and a spacious outdoor patio. Known for a welcoming, laid-back atmosphere for dogs and their owners.",
    "dogRules": "Leashed dogs welcome on the outdoor patio only. Dog menu of grilled chicken strips or ground beef with white rice; half-off doggie meals on Tuesdays.",
    "amenities": ["Outdoor patio", "Shade", "Dog menu", "Water bowls", "Parking"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Nico's Pier 38",
    "lat": 21.3095,
    "lng": -157.8747,
    "type": "leashed",
    "category": "patio",
    "address": "1129 N Nimitz Hwy, Honolulu, HI 96817",
    "hours": "Mon-Sat 6:30am-9pm, Sun 10am-9pm",
    "description": "An award-winning seafood restaurant beside the Honolulu fish auction with a sun-soaked covered terrace overlooking the harbor. Live music plays through the day.",
    "dogRules": "Leashed dogs welcome on the outdoor terrace/patio only, not inside the dining room.",
    "amenities": ["Outdoor patio", "Covered seating", "Harbor views", "Parking", "Live music"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Barefoot Beach Cafe",
    "lat": 21.2653,
    "lng": -157.8228,
    "type": "leashed",
    "category": "patio",
    "address": "2699 Kalakaua Ave, Honolulu, HI 96815",
    "hours": "Daily 8am-7:30pm",
    "description": "A casual beachfront cafe at Queen's Surf Beach near Kapiolani Park with open-air picnic tables, ocean views and live music. Serves American and Hawaiian plates.",
    "dogRules": "Leashed, well-behaved dogs welcome at the outdoor patio/picnic tables. Plenty of shade; BYOB permitted.",
    "amenities": ["Outdoor patio", "Beachfront", "Shade", "Ocean views", "Near dog-friendly park"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Merriman's Honolulu",
    "lat": 21.2938,
    "lng": -157.8558,
    "type": "leashed",
    "category": "patio",
    "address": "1108 Auahi St, Honolulu, HI 96814",
    "hours": "Daily 11am-9pm",
    "description": "An upscale farm-to-table restaurant in Ward Village's Anaha tower with a large half-lanai and daily happy hour. Emphasizes locally sourced Hawaii ingredients.",
    "dogRules": "Leashed dogs welcome on the outdoor lanai seating only.",
    "amenities": ["Outdoor lanai", "Shade", "Happy hour", "Water bowls"],
    "region": "Honolulu",
    "uncertain": true
  },
  {
    "name": "Istanbul Hawaii",
    "lat": 21.2939,
    "lng": -157.8556,
    "type": "leashed",
    "category": "patio",
    "address": "1108 Auahi St #152, Honolulu, HI 96814",
    "hours": "Tue-Sun 10am-9pm, closed Mon",
    "description": "A modern Turkish and Mediterranean restaurant in the Anaha building in Kaka'ako with generous outdoor seating and ample spacing between tables.",
    "dogRules": "Leashed dogs welcome at outdoor tables only. Plenty of shade and space between tables.",
    "amenities": ["Outdoor patio", "Shade", "Water bowls"],
    "region": "Honolulu",
    "uncertain": true
  },
  {
    "name": "Artizen by MW",
    "lat": 21.2969,
    "lng": -157.8524,
    "type": "leashed",
    "category": "patio",
    "address": "888 Kapiolani Blvd #102, Honolulu, HI 96813",
    "hours": "Mon-Fri 10am-2pm (lunch), varies",
    "description": "A casual local eatery from MW Restaurant in the Symphony Honolulu building, serving locally sourced comfort food with outdoor seating along Ward Avenue.",
    "dogRules": "Leashed dogs welcome on the outdoor patio only. Offers 'Echigo's Four-Legged Menu' with pork or chicken and farm vegetables.",
    "amenities": ["Outdoor patio", "Dog menu", "Shade", "Water bowls"],
    "region": "Honolulu",
    "uncertain": false
  },
  {
    "name": "Appetito Craft Pizza & Wine Bar",
    "lat": 21.2785,
    "lng": -157.8267,
    "type": "leashed",
    "category": "patio",
    "address": "150 Kaiulani Ave, Honolulu, HI 96815",
    "hours": "Daily 4pm-9:30pm",
    "description": "An Italian craft pizza and wine bar in Waikiki with sidewalk outdoor seating and an affordable happy hour.",
    "dogRules": "Leashed dogs welcome at the outdoor tables only.",
    "amenities": ["Outdoor patio", "Happy hour", "Water bowls"],
    "region": "Honolulu",
    "uncertain": true
  },
  {
    "name": "Encore Saloon",
    "lat": 21.3130,
    "lng": -157.8615,
    "type": "leashed",
    "category": "patio",
    "address": "10 N Hotel St, Honolulu, HI 96817",
    "hours": "Daily 11am-10pm",
    "description": "A Mexican restaurant and mezcal bar in Chinatown with an enclosed outdoor courtyard, known for tacos and Taco Tuesday specials.",
    "dogRules": "Leashed dogs welcome in the outdoor courtyard only.",
    "amenities": ["Outdoor courtyard", "Shade", "Water bowls"],
    "region": "Honolulu",
    "uncertain": true
  },
  {
    "name": "Off the Wall Craft Beer & Wine",
    "lat": 21.2936,
    "lng": -157.8567,
    "type": "leashed",
    "category": "patio",
    "address": "1170 Auahi St, Honolulu, HI 96814",
    "hours": "Daily 11am-10pm",
    "description": "A self-serve craft beer, cider and wine tap bar inside South Shore Market in Ward Village, with a quiet outdoor seating area.",
    "dogRules": "Leashed dogs welcome in the outdoor seating area only.",
    "amenities": ["Outdoor patio", "Self-serve taps", "Shade"],
    "region": "Honolulu",
    "uncertain": true
  },
  {
    "name": "Lulu's Waikiki",
    "lat": 21.2704,
    "lng": -157.8213,
    "type": "leashed",
    "category": "patio",
    "address": "2586 Kalakaua Ave, Honolulu, HI 96815",
    "hours": "Daily 7am-12am",
    "description": "A lively second-floor bar and grill in the Park Shore Waikiki across from Kuhio Beach, with an open-air balcony overlooking the ocean and Diamond Head.",
    "dogRules": "Leashed dogs welcome at the upstairs open-air patio tables only.",
    "amenities": ["Outdoor patio", "Ocean views", "Shade", "Water bowls"],
    "region": "Honolulu",
    "uncertain": true
  },
  {
    "name": "Maui Brewing Co. Waikiki",
    "lat": 21.2797,
    "lng": -157.8288,
    "type": "leashed",
    "category": "patio",
    "address": "2300 Kalakaua Ave, Honolulu, HI 96815",
    "hours": "Daily 11am-11pm",
    "description": "A large open-air brewpub inside the Outrigger Waikiki Beachcomber Hotel with 36+ craft beers on tap and island-inspired dishes like fish tacos, pizzas and burgers.",
    "dogRules": "Leashed dogs welcome in the open-air seating area. Confirm current policy with staff on arrival.",
    "amenities": ["Open-air seating", "Craft beer", "Shade", "Water bowls"],
    "region": "Honolulu",
    "uncertain": true
  },
  {
    "name": "Arnold's Beach Bar & Grill",
    "lat": 21.2823,
    "lng": -157.8330,
    "type": "leashed",
    "category": "patio",
    "address": "339 Saratoga Rd, Honolulu, HI 96815",
    "hours": "Daily 11am-12am",
    "description": "A tiki-style dive bar near Fort DeRussy in Waikiki with a covered outdoor patio, tropical drinks and daily live music.",
    "dogRules": "Leashed dogs welcome at the covered outdoor patio tables only.",
    "amenities": ["Outdoor patio", "Covered seating", "Live music", "Water bowls"],
    "region": "Honolulu",
    "uncertain": true
  },
  {
    "name": "Puka's Bar at Kahala Whole Foods",
    "lat": 21.2760,
    "lng": -157.7887,
    "type": "leashed",
    "category": "patio",
    "address": "4211 Waialae Ave, Honolulu, HI 96816",
    "hours": "Daily 11am-8pm",
    "description": "An outdoor bar attached to the Whole Foods Market at Kahala Mall in East Honolulu, serving local beer, wine and bar bites on a shaded patio.",
    "dogRules": "Leashed dogs welcome on the outdoor patio only. Offers a dog menu with hot dogs, mini burgers and bacon.",
    "amenities": ["Outdoor patio", "Dog menu", "Shade", "Water bowls", "Parking"],
    "region": "East Honolulu",
    "uncertain": false
  },
  {
    "name": "Morning Brew Coffee & Bistro (Kailua)",
    "lat": 21.3924,
    "lng": -157.7400,
    "type": "leashed",
    "category": "patio",
    "address": "600 Kailua Rd #120, Kailua, HI 96734",
    "hours": "Daily 6am-6pm",
    "description": "A cozy Kailua coffeehouse serving local Hawaii coffees since 1995, with breakfast standards, sandwiches and baked goods and dog-friendly seats outside.",
    "dogRules": "Leashed dogs welcome at the outdoor seats only.",
    "amenities": ["Outdoor seating", "Shade", "Water bowls", "Parking"],
    "region": "Windward",
    "uncertain": false
  },
  {
    "name": "Nalu Health Bar & Cafe (Kailua)",
    "lat": 21.3935,
    "lng": -157.7425,
    "type": "leashed",
    "category": "patio",
    "address": "131 Hekili St #109, Kailua, HI 96734",
    "hours": "Daily 8am-6pm",
    "description": "A health-focused cafe in Kailua serving smoothies, fresh juices, acai bowls, ahi wraps and kale salads, with a small dog-friendly outdoor seating area out front.",
    "dogRules": "Leashed dogs welcome at the small outdoor bar/seating area out front (seats about four).",
    "amenities": ["Outdoor seating", "Shade", "Water bowls"],
    "region": "Windward",
    "uncertain": false
  },
  {
    "name": "Uncle Bo's Haleiwa",
    "lat": 21.5924,
    "lng": -158.1039,
    "type": "leashed",
    "category": "patio",
    "address": "66-111 Kamehameha Hwy #101, Haleiwa, HI 96712",
    "hours": "Daily 4pm-10pm",
    "description": "A North Shore outpost of the popular Honolulu restaurant, serving pupus and island comfort food with an easygoing vibe and outdoor seating in Haleiwa town.",
    "dogRules": "Leashed dogs welcome in the outdoor seating area only.",
    "amenities": ["Outdoor seating", "Shade", "Water bowls", "Parking"],
    "region": "North Shore",
    "uncertain": true
  },
  {
    "name": "Green World Coffee Farm",
    "lat": 21.5388,
    "lng": -158.0330,
    "type": "leashed",
    "category": "patio",
    "address": "71-101 Kamehameha Hwy, Wahiawa, HI 96786",
    "hours": "Daily 7am-6pm",
    "description": "A working coffee farm and cafe set on seven acres of gardens with over 2,000 arabica trees, on the Kamehameha Highway between Wahiawa and the North Shore. Serves estate coffee and espresso drinks.",
    "dogRules": "Leashed dogs welcome at the outdoor cafe tables and around the garden grounds.",
    "amenities": ["Outdoor seating", "Garden grounds", "Shade", "Parking"],
    "region": "Central Oahu",
    "uncertain": false
  },
  {
    "name": "Lanikai Beach",
    "lat": 21.3918,
    "lng": -157.7148,
    "type": "leashed",
    "category": "beach",
    "address": "Mokulua Drive (public rights-of-way), Kailua, HI 96734",
    "hours": "Open daily, dawn to dusk (public shoreline access)",
    "description": "A famous half-mile of soft white sand and turquoise water fronting a residential neighborhood, with views of the Mokulua islands. Accessed via public beach right-of-way paths.",
    "dogRules": "Leashed dogs are allowed on the sand. This is state-jurisdiction shoreline fronting a residential area with no City beach-park prohibition and no wildlife-sanctuary designation. Keep dogs clear of any hauled-out monk seals.",
    "amenities": ["Street parking", "Calm swimming", "Public beach access paths"],
    "region": "Windward",
    "uncertain": false
  },
  {
    "name": "Kahala Beach",
    "lat": 21.2683,
    "lng": -157.7802,
    "type": "leashed",
    "category": "beach",
    "address": "Kahala Avenue (public access paths), Honolulu, HI 96816",
    "hours": "Open daily, dawn to dusk (public shoreline access)",
    "description": "A quiet, uncrowded upscale beach stretching along Kahala Avenue, reached through public shoreline access paths between homes. Shallow and calm, good for wading.",
    "dogRules": "Leashed dogs are allowed on this state-jurisdiction residential shoreline, which is not a City beach park and carries no sanctuary designation.",
    "amenities": ["Street parking", "Public beach access paths", "Calm swimming"],
    "region": "East Honolulu",
    "uncertain": false
  },
  {
    "name": "Ka'alawai Beach",
    "lat": 21.2566,
    "lng": -157.7994,
    "type": "leashed",
    "category": "beach",
    "address": "Kulamanu Place (public access), off Diamond Head Road, Honolulu, HI 96816",
    "hours": "Open daily, dawn to dusk (public shoreline access)",
    "description": "A narrow local beach at the base of Diamond Head near Black Point, with good snorkeling on the reef and a mostly residential, low-key feel.",
    "dogRules": "Leashed dogs are commonly permitted on this state-jurisdiction shoreline, which is not a City beach park and has no sanctuary designation. Not confirmed by a specific City ordinance, so verify posted signs on arrival.",
    "amenities": ["Street parking", "Snorkeling"],
    "region": "East Honolulu",
    "uncertain": true
  },
  {
    "name": "Kawela Bay Beach",
    "lat": 21.7028,
    "lng": -158.0111,
    "type": "leashed",
    "category": "beach",
    "address": "Kamehameha Highway (trail access near Turtle Bay), Kahuku, HI 96731",
    "hours": "Open daily, dawn to dusk (public shoreline access)",
    "description": "A secluded, tree-shaded North Shore bay with calm, protected water reached by a short walk through ironwood and banyan trees. Sea turtles and occasional monk seals frequent the bay.",
    "dogRules": "Leashed dogs are commonly permitted on this state-jurisdiction shoreline. Keep well clear of resting turtles and monk seals, which are federally protected. Not confirmed by a specific City ordinance, so verify posted signs.",
    "amenities": ["Trail access", "Shade trees", "Calm swimming"],
    "region": "North Shore",
    "uncertain": true
  },
  {
    "name": "Turtle Bay Beach",
    "lat": 21.7003,
    "lng": -157.9931,
    "type": "leashed",
    "category": "beach",
    "address": "57-091 Kamehameha Highway, Kahuku, HI 96731",
    "hours": "Open daily, dawn to dusk (public shoreline access)",
    "description": "A protected sandy cove at the northernmost point of Oahu beside the Turtle Bay Resort, with a reef-sheltered swimming area and coastal trail access.",
    "dogRules": "Leashed dogs are commonly permitted on this state-jurisdiction shoreline (public beach below the high wash line). Resort-managed upland areas may set their own rules, so verify posted signs.",
    "amenities": ["Parking", "Restrooms nearby", "Snorkeling", "Coastal trail"],
    "region": "North Shore",
    "uncertain": true
  }
];
